# https://github.com/elastic/apm-server/blob/master/apm-server.yml
apm-server:
  host: "0.0.0.0:8200"
  secret: "d910fe18cd0fde99ee282685cc7046e14a8491df474b85c8"


setup.kibana:
  host: "172.17.0.1:5601"
  username: "elastic"
  password: "123456"


output.elasticsearch:
  hosts: ["172.17.0.1:9200"]
  username: "elastic"
  password: "123456"
  indices:
    - index: "apm-%{[beat.version]}-sourcemap"
      when.contains:
        processor.event: "sourcemap"

    - index: "apm-%{[beat.version]}-error-%{+yyyy.MM.dd}"
      when.contains:
        processor.event: "error"

    - index: "apm-%{[beat.version]}-transaction-%{+yyyy.MM.dd}"
      when.contains:
        processor.event: "transaction"

    - index: "apm-%{[beat.version]}-span-%{+yyyy.MM.dd}"
      when.contains:
        processor.event: "span"

apm-server.rum.enabled: true
apm-server.rum.event_rate.limit: 300
apm-server.rum.event_rate.lru_size: 1000
apm-server.rum.allow_origins: ['*']
apm-server.rum.library_pattern: "node_modules|bower_components|~"
apm-server.rum.exclude_from_grouping: "^/webpack"
apm-server.rum.source_mapping.cache.expiration: 5m
apm-server.rum.source_mapping.index_pattern: "apm-*-sourcemap*"
