version: '2.2'
services:
  kb_72:
    container_name: kb72
    image: docker.elastic.co/kibana/kibana:7.2.0
    volumes:
      - ./kibana.yml:/usr/share/kibana/config/kibana.yml
    ports:
      - 5601:5601
    networks:
      - esnet

networks:
  esnet:
